#服务端口server:
server:
  port: 8443
  ssl:
    key-store: classpath:properties/keystore.p12
    key-store-password: gw123456
    key-password: gw123456

http:
  port: 8080

#基础配置
spring:
  application:
    name: SpringBootDemp-app #指定应用的名字
  datasource:
    test1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://39.105.75.88:3306/commerce?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: q123456789
      druid:
        #初始化大小，最小，最大
        initial-size: 5
        min-idle: 10
        max-active: 200
        #配置获取连接等待超时的时间
        max-wait: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 30000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        #合并多个DruidDataSource的监控数据
        use-global-data-source-stat: true
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    test2:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://39.105.75.88:3306/commerce?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: q123456789
      druid:
        #初始化大小，最小，最大
        initial-size: 5
        min-idle: 10
        max-active: 200
        #配置获取连接等待超时的时间
        max-wait: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 30000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        #合并多个DruidDataSource的监控数据
        use-global-data-source-stat: true
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
  thymeleaf:
    cache: true
    check-template: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    excluded-view-names:
  devtools:
    remote:
      restart:
        enabled: true
  redis:
    host: localhost
    port: 6379
    password: gw123456
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 1000
      #连接池中的最大空闲连接
      min-idle: 10
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
    #连接超时时间（毫秒）
    timeout: 2000

# Mybatis 插件
mybatis:
  type-aliases-package: com.example.base
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true

# 通用 Mapper 配置
mapper:
    mappers:
        - tk.mybatis.mapper.common.Mapper
    not-empty: false
    identity: MYSQL

#打印sql信息
logging:
  config: classpath:logback-spring.xml
