#服务端口server:
server:
    port: 8888

#基础配置
spring:
  application:
    name: SpringBootDemp-app #指定应用的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/commerce?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: q123456789
    druid:
      #初始化大小，最小，最大
      initial-size: 5
      min-idle: 10
      max-active: 200
      #配置获取连接等待超时的时间
      max-wait: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
  redis:
    host: localhost
    port: 6379
    password: gw123456
    pool:
    #连接池最大连接数（使用负值表示没有限制）
    max-active: 1000
    #连接池中的最大空闲连接
    min-idle: 10
    #连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    #连接超时时间（毫秒）
    timeout: 2000

#打印sql信息
logging:
  config: classpath:logback-spring.xml
