server:
  port: 8081
spring:
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: 123456

# tag::configuration-eureka[]
eureka:   #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health #2.0后actuator的地址发生了变化
    metadata-map:
      "user.name": ${spring.security.user.name}         #These two are needed so that the server
      "user.password": ${spring.security.user.password} #can access the protected client endpoints
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://root:123456@localhost:8761}/eureka/

# 2.0开始，actuator默认不开放，所以要设置为开放
management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS
# end::configuration-eureka[]

#-----------------------编写者相关信息----------------------
info:
  owner: guangwei
  version: '@project.version@'
  app:
    name: "@project.name@"
    version: "@project.version@"
    description: "@project.description@"