server:
  port: 8081
spring:
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: 123456
  mail:
    # 发送邮件服务器
    host: smtp.qq.com
    # QQ邮箱
    username: 2477304354@qq.com
    # 客户端授权码 opvjwamgyknkebce
    password: ifedyxsnjtmgechf
    # 发送邮件协议
    protocol: smtp
    properties:
      mail.debug: false
      # 安全认证(默认是true)
      mail.smtp.auth: true
      # 端口号465或587
      mail.smtp.port: 465
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      # 开启ssl加密 否则项目启动时报530error
      mail.smtp.ssl.enable: true
      # mail.smtp.ssl.socketFactory: sf
      # 可以任意
      mail.display.sendmail: Javen
      # 可以任意
      mail.display.sendname: Spring Boot Guide Email
    default-encoding: UTF-8
  boot:
    admin:
      notify:
        mail:
          from: 2477304354@qq.com
          to: yemingrujing@163.com

# tag::configuration-eureka[]
eureka:   #<1>
  instance:
    #2.0后actuator的地址发生了变化
    leaseRenewalIntervalInSeconds: 10
    secure-health-check-url: http://localhost:${server.port}/actuator/health
    metadata-map:
      #These two are needed so that the server
      "user.name": ${spring.security.user.name}
      #can access the protected client endpoints
      "user.password": ${spring.security.user.password}
    hostname: localhost
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://root:123456@localhost:8761}/eureka/,${EUREKA_SERVICE_URL:http://root:123456@localhost:8762}/eureka/

# 2.0开始，actuator默认不开放，所以要设置为开放
management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS
# end::configuration-eureka[]

#-----------------------编写者相关信息----------------------
info:
  owner: guangwei
  version: '@project.version@'
  app:
    name: "@project.name@"
    version: "@project.version@"
    description: "@project.description@"